name: Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx nuxi generate
      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: webumenia.sk
          fingerprint: "2J8XrBxXtH+d+8RvvPfYptm5KeKlomT7BjkoMwPOvWA"
          source: .output/public/*
          target: /var/www/sakra-stex
